May 17, 08:41:44 AM: 71343bcc Duration: 717.36 ms	Memory Usage: 132 MB
May 17, 08:41:44 AM: 9c3959ad Duration: 731.57 ms	Memory Usage: 135 MB
May 17, 08:41:44 AM: 9b11f8dc Duration: 736.72 ms	Memory Usage: 128 MB
May 17, 08:41:45 AM: d912ad11 Duration: 243.07 ms	Memory Usage: 158 MB
May 17, 08:41:45 AM: 7c058d4f Duration: 330.44 ms	Memory Usage: 158 MB
May 17, 08:42:06 AM: 13136316 Duration: 143.56 ms	Memory Usage: 158 MB
May 17, 08:42:06 AM: 8c79d0c0 Duration: 148.53 ms	Memory Usage: 159 MB
May 17, 08:42:06 AM: 2d798ecc INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:42:07 AM: 6322a0d5 Duration: 71.03 ms	Memory Usage: 158 MB
May 17, 08:42:08 AM: 2d798ecc INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s0\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:08 AM: 2d798ecc ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s0\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:42:08 AM: 2d798ecc Duration: 1880.73 ms	Memory Usage: 159 MB
May 17, 08:42:08 AM: 669a3037 INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:42:09 AM: 669a3037 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:09 AM: 669a3037 ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:42:09 AM: 669a3037 Duration: 235.63 ms	Memory Usage: 159 MB
May 17, 08:42:10 AM: 2da4adf0 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s2\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:10 AM: 2da4adf0 ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s2\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:42:10 AM: 2da4adf0 Duration: 748.94 ms	Memory Usage: 161 MB
May 17, 08:42:46 AM: 68923c2b INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:42:46 AM: 68923c2b INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s3\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:46 AM: 68923c2b ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s3\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:42:46 AM: 68923c2b Duration: 444.21 ms	Memory Usage: 163 MB
May 17, 08:42:47 AM: 6ee4e6e2 INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:42:47 AM: 6ee4e6e2 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s4\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:47 AM: 6ee4e6e2 ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s4\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:42:47 AM: 6ee4e6e2 Duration: 224.66 ms	Memory Usage: 163 MB
May 17, 08:42:47 AM: 88348f65 Duration: 70.88 ms	Memory Usage: 163 MB
May 17, 08:42:48 AM: 57422ff9 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s5\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:48 AM: 57422ff9 ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s5\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:42:48 AM: 57422ff9 Duration: 499.06 ms	Memory Usage: 163 MB
May 17, 08:42:51 AM: d8ac7a8b INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:42:51 AM: d8ac7a8b INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s6\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:51 AM: d8ac7a8b ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s6\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:42:51 AM: d8ac7a8b Duration: 225.22 ms	Memory Usage: 163 MB
May 17, 08:42:52 AM: f9b402ef INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:42:52 AM: f9b402ef INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s7\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:52 AM: f9b402ef ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s7\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:42:52 AM: f9b402ef Duration: 224.49 ms	Memory Usage: 163 MB
May 17, 08:42:53 AM: 2672d167 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s8\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:42:53 AM: 2672d167 ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s8\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:42:53 AM: 2672d167 Duration: 560 ms	Memory Usage: 163 MB
May 17, 08:42:53 AM: 9dbf4f4b Duration: 72.31 ms	Memory Usage: 165 MB
May 17, 08:42:56 AM: 716cefb1 INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:42:57 AM: 716cefb1 INFO   GET /api/user/role - Database response: { role: 'USER' }
May 17, 08:42:57 AM: 716cefb1 Duration: 435.84 ms	Memory Usage: 166 MB
May 17, 08:42:58 AM: 7bc24682 Duration: 713.7 ms	Memory Usage: 166 MB
May 17, 08:42:58 AM: 63fc680a Duration: 17.85 ms	Memory Usage: 167 MB
May 17, 08:42:58 AM: 4e1ebdf7 Duration: 25.8 ms	Memory Usage: 167 MB
May 17, 08:42:58 AM: 45e10fd5 Duration: 17.04 ms	Memory Usage: 168 MB
May 17, 08:42:58 AM: 438fb2d3 Duration: 153.43 ms	Memory Usage: 158 MB
May 17, 08:42:58 AM: 32c1f653 Duration: 356.11 ms	Memory Usage: 154 MB
May 17, 08:43:01 AM: 623e1ff8 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s0\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:43:01 AM: 623e1ff8 ERROR  Error fetching user profile: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s0\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async c (/var/task/.next/server/app/api/user/profile/route.js:1:1419)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:43:01 AM: 623e1ff8 Duration: 2251.61 ms	Memory Usage: 154 MB
May 17, 08:43:04 AM: f0c89162 Duration: 131.43 ms	Memory Usage: 154 MB
May 17, 08:43:16 AM: e300476c INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:43:16 AM: e300476c INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:43:16 AM: e300476c ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s1\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:43:16 AM: e300476c Duration: 428.12 ms	Memory Usage: 154 MB
May 17, 08:43:17 AM: 2a58140e INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s2\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:43:17 AM: 2a58140e ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s2\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:43:17 AM: 2a58140e Duration: 560.44 ms	Memory Usage: 154 MB
May 17, 08:43:41 AM: 5f5322dc INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:43:42 AM: 5f5322dc INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s3\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:43:42 AM: 5f5322dc ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s3\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:43:42 AM: 5f5322dc Duration: 436.59 ms	Memory Usage: 154 MB
May 17, 08:43:43 AM: c0fa48cd INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s4\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:43:43 AM: c0fa48cd ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s4\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:43:43 AM: c0fa48cd Duration: 505.76 ms	Memory Usage: 154 MB
May 17, 08:43:48 AM: ad289900 Duration: 82.24 ms	Memory Usage: 154 MB
May 17, 08:43:52 AM: b2d1b8a4 INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:43:52 AM: b2d1b8a4 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s5\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:43:52 AM: b2d1b8a4 ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s5\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:43:52 AM: b2d1b8a4 Duration: 218.24 ms	Memory Usage: 154 MB
May 17, 08:43:53 AM: fe7711e7 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s6\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:43:53 AM: fe7711e7 ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s6\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:43:53 AM: fe7711e7 Duration: 555.8 ms	Memory Usage: 154 MB
May 17, 08:44:01 AM: c00d2abe INFO   GET /api/user/role - Request: { userId: '608ad4b8-56e4-49ee-9c24-b0a9a1b2bfab' }
May 17, 08:44:01 AM: c00d2abe INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s7\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:44:01 AM: c00d2abe ERROR  GET /api/user/role - Error: PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s7\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async u (/var/task/.next/server/app/api/user/role/route.js:1:780)
    at async /var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async doRender (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1333:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/base-server.js:1555:28) {
  clientVersion: '5.22.0'
}
May 17, 08:44:01 AM: c00d2abe Duration: 422.5 ms	Memory Usage: 154 MB
May 17, 08:44:02 AM: 8ef6110e INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s8\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:44:02 AM: 8ef6110e ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s8\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:44:02 AM: 8ef6110e Duration: 495.07 ms	Memory Usage: 154 MB
May 17, 08:44:08 AM: 8c76f473 INFO   prisma:error 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s9\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
May 17, 08:44:08 AM: 8c76f473 ERROR  PrismaClientUnknownRequestError: 
Invalid `prisma.user.findUnique()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s9\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at $n.handleRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:7505)
    at $n.handleAndLogRequestError (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6623)
    at $n.request (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:121:6307)
    at async l (/var/task/node_modules/.pnpm/@prisma+client@5.22.0_prisma@5.22.0/node_modules/@prisma/client/runtime/library.js:130:9633)
    at async g (/var/task/.next/server/chunks/7325.js:1:7977) {
  clientVersion: '5.22.0'
}
May 17, 08:44:08 AM: 8c76f473 Duration: 494.08 ms	Memory Usage: 154 MB